### ISSUE TITLE
MaxSeqLength

### ISSUE THREAD

**Issue by colindaven** [cmdcolin/gccontent#3]
Hi Colin,

I think it might be appropriate to have an  max chunk / maxSize parameter.

On a 16GB i7 laptop I am experiencing problems with chrome (many crashes) and firefox (few, but still some crashes) while looking at GC content in chromosomes of around 50Mbp.  On firefox the whole browser can go down, on chrome the tab dies.

It probably only makes sense to look at GC in regions of <5Mbp or <10Mbp. The danger is if a user is looking at GC in a small region then switches to another (zoomed out) chromosome view the browser may go down, or become inactive for (in my brief testing) 60seconds +.

This is with the JBrowse/Store/SeqFeature/SequenceChunks storeClass.

Best wishes,
Colin

**Comment by cmdcolin** [comment]
Sounds about right! Luckily the default "sequence" class has a good method of handling this that I can port over

**Comment by cmdcolin** [comment]
Also just as a technical note, the sequence class uses the current zoom level/"scale" instead of an explicit chunk size. I pushed cc491ff as a possible fix now though

**Comment by colindaven** [comment]
Nice one - thanks!
