### ISSUE TITLE
display is off by one 

### ISSUE THREAD

**Issue by childers** [cmdcolin/gccontent#4]
The display has an off-by-one issue, which isn't really obvious unless the windowsize and windowdelta are set to 1.  Below is a screenshot with a BigWig GC track "GC Content" and below that the GCContent plugin based of the sequenceChunk.
```shell
  "maxExportSpan": 500000,
  "autoscale": "global",
  "logScaleOption": false,
  "style": {
    "height": 31,
    "pos_color": "#0000ff",
    "neg_color": "#ffff00",
    "bg_color": "rgba(230,230,230,1)",
    "clip_marker_color": "black"
  },
  "min_score": 0,
  "max_score": 1,
  "windowSize": 1,
  "windowDelta": 1,
  "gcMode": "content",
  "bicolor_pivot": 0.5,
  "scoreType": "avgScore",
  "storeClass": "JBrowse/Store/SeqFeature/SequenceChunks",
  "urlTemplate": "seq/{refseq_dirpath}/{refseq}-",
  "label": "GCContent",
  "type": "GCContent/View/Track/GCContent",
```

<img width="388" alt="screen shot 2017-07-06 at 4 26 49 pm" src="https://user-images.githubusercontent.com/421248/27931550-91408504-6268-11e7-8076-a15517f42116.png">

**Comment by cmdcolin** [comment]
Added a potential fix on master, feel free to try out :)

**Comment by childers** [comment]
This looks like it fixed the off-by-one issue.  Thanks!

<img width="746" alt="screen shot 2017-07-10 at 1 13 49 pm" src="https://user-images.githubusercontent.com/421248/28030420-b4b61b00-6571-11e7-8655-954edc355073.png">
