### ISSUE TITLE
Ambiguous bases are displaying as AT

### ISSUE THREAD

**Issue by childers** [cmdcolin/gccontent#5]
Runs of N's are counted as 0, and look like runs of A/T. I really like this plugin, as it would save us from manually building GC (and gap) bigwigs. 

Below the image includes a bigwig GC Content track, in addition to the GCContent track made using the plugin. A BigWig track showing sequence gaps shown as runs of N is the bottom track.

<img width="388" alt="screen shot 2017-07-06 at 4 26 49 pm" src="https://user-images.githubusercontent.com/421248/27931550-91408504-6268-11e7-8076-a15517f42116.png">

**Comment by cmdcolin** [comment]
A possible fix for this also on master now, feel free to give it a try

**Comment by cmdcolin** [comment]
Was this resolved? I think now there is no gccontent data is drawn inside gaps

**Comment by childers** [comment]
It looks like it is working great now.  Thank you!
![screen shot 2017-08-03 at 4 07 03 pm](https://user-images.githubusercontent.com/421248/28941394-e597327a-7865-11e7-80ac-687651a9b28d.png)

**Comment by cmdcolin** [comment]
Super. I also just added to the latest master a maxZoom parameter for the density track (it already existed on the xy track) so it will display "Zoom in to see GC content" at over a ~1.5MB zoom level (adjustable using the config parameter maxZoom, but if you are calculating over that big regions like this it can slow down browser). Feel free to test out

**Comment by childers** [comment]
It does slow things down a fair bit on really large views. so the max size cap is helpful.
