### ISSUE TITLE
GC-XY track not loading in only one of many genomes

### ISSUE THREAD

**Issue by srobb1** [cmdcolin/gccontent#9]
Hi Colin,

I am not sure what I have done. I have the GC-XY working in other genomes loaded into my JBrowse install. This one genome I have, it is not loading, just says loading.... I have double checked that my GC config is the same, it is. I am not sure what is going on. 

If you want to poke around, I have created a login for you. Email me at smr@stowers.org and i will send you account info.

Thanks,
Sofia

**Comment by cmdcolin** [comment]
was fixed by  https://github.com/elsiklab/gccontent/commit/bc3662580d207e7c32586d53f3707b2476c7c04e  after email correspondence awhile back :)
